### PR TITLE
Fix for #3.

### PR DESCRIPTION
**Pull request by bbaassssiiee**

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
The travis config creates the error with roles_path in ansible.cfg, causing the build to fail.

**Comment by joeyfeldberg** [comment]
This is still not pushed to ansible-galaxy

**Comment by mariussturm** [comment]
@lesmyrmidons any chance to get this pushed to Galaxy?

**Comment by bbaassssiiee** [comment]
Elastic did it! https://galaxy.ansible.com/elastic/elasticsearch/

**Pull request merged**
